ТЗ10. Реализованы функции добавления в друзья, оценки фильмов
VladislavKubarev/java-filmorate pull request #3
Opened 2023-05-14 20:22 UTC by VladislavKubarev

2023-05-15 19:06 UTC, alexache requested changes

2023-05-15 19:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (releaseDateValidation(film)) {
Валидации желательно делать сразу в контроллере, особенно те, которые не требуют обращения к хранилищу - иначе зачем затягивать возврат ошибки обратно клиенту?

2023-05-15 19:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private boolean releaseDateValidation(Film film) {
По логике тогда и не нужно возвращать из этого метода, Если валидация не проходит, тогда бросается исключение, зачем еще и возвращать true?

2023-05-15 19:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public User createUser(User user) {
В сторадже пользователей схожие комментарии со стораджем фильмов

2023-05-15 19:06 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        userService.createUser(testUser);
Это не очень закономерное изменение - клиенты по сути так и будут работать с контроллером, зачем заменять это на сервис?

2023-05-16 10:20 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Film film = filmStorage.getFilmById(filmId);
Исправлено в filmService и userService

2023-05-16 10:21 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +
Исправлено

2023-05-16 10:21 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private boolean releaseDateValidation(Film film) {
Исправлено

2023-05-16 10:21 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public User createUser(User user) {
Исправлено

2023-05-16 10:25 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Collections.sort(popularFilm, new Comparator<Film>() {
Не исправлено. Вернусь к этому на следующем ТЗ.

2023-05-16 10:49 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (releaseDateValidation(film)) {
Исправлено

2023-05-16 11:11 UTC, VladislavKubarev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        userService.createUser(testUser);
Исправлено

2023-05-16 20:47 UTC, alexache approved these changes

2023-06-03 17:21 UTC, merged