ТЗ11. Добавлена база данных, добавлены рейтинги и жанры фильмов.
VladislavKubarev/java-filmorate pull request #5
Opened 2023-06-10 08:59 UTC by VladislavKubarev

2023-06-10 21:05 UTC, alexache requested changes

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(resultSet.getInt("mpa_id")));
Запросы к базе в цикле плохо (данный метод вызывается в цикле по списку фильмов). МПА можно получать джоином, а жанры отдельным запросом по списку фильмов одним разом

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.setGenres(film.getGenres().stream().map(g -> getGenreById(g.getId()))
Опять же запросы к базе в цикле, для чего это, если объект жанра есть?

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        if (doesTheGenreExist(genreId)) {
Разве по селекту и так не будет видно, существует жанр или нет

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +@Component
@Repository и так по сути разновидность @Component. Нет смысла иметь обе аннотации

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        if (doesTheMpaExist(id)) {
Тоже можно бы обойтись без доп проверки

2023-06-10 21:05 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +@Component
Тоже лишнее

2023-06-11 17:11 UTC, VladislavKubarev commented on src/main/resources/schema.sql
> +login VARCHAR NOT NULL,
исправлено

2023-06-11 17:13 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        return friendsStorage.showFriendsList(user).stream().map(userStorage::getUserById).collect(Collectors.toList());
исправил на запрос с подзапросом

2023-06-11 17:13 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        return friendsStorage.showFriendsList(user).stream()
исправил на запрос с подзапросом

2023-06-11 17:13 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(film.getMpa().getId()));
убрал setMpa

2023-06-11 17:14 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(resultSet.getInt("mpa_id")));
не совсем понял, что здесь требуется

2023-06-11 17:15 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.setGenres(film.getGenres().stream().map(g -> getGenreById(g.getId()))
исправил, не уверен, что правильно

2023-06-11 17:18 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        if (doesTheGenreExist(genreId)) {
изменил на try catch

2023-06-11 17:40 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        if (doesTheMpaExist(id)) {
исправил на try catch

2023-06-11 19:50 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +@Component
исправил

2023-06-11 19:50 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +@Component
исправил

2023-06-11 20:45 UTC, alexache requested changes

2023-06-11 20:45 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(resultSet.getInt("mpa_id")));
mapRowToFilm вызывается из showAllFilms, то есть в цикле. Запросы в цикле запрещены - значит в данном методе не должно быть никаких запросов к базе.
 МПА нужно делать джоином в первоначалальном запросе
жанры нужно получать отдельным (одним) запросом по списку (или одному) фильму

2023-06-11 20:45 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/FriendsDbStorage.java
> +                "(select friend_id from friends where user_id = ?)" +
Почему не через джоины? Подзапросы в большом количестве - не самая лучшая идея

2023-06-11 20:45 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        genres.forEach(genre -> jdbcTemplate.update(sqlQuery, film.getId(), genre.getId()));
Запрос к базе в цикле, а нужен 1 батч запрос на обновление сразу множества записей

2023-06-12 09:12 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        genres.forEach(genre -> jdbcTemplate.update(sqlQuery, film.getId(), genre.getId()));
исправил на batchUpdate

2023-06-12 09:57 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(resultSet.getInt("mpa_id")));
mpa исправил на join, у genre есть запрос на получение списка жанров по id фильма, оставил его в mapRowToFilm, не знаю правильно или нет

2023-06-12 11:18 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/FriendsDbStorage.java
> +                "(select friend_id from friends where user_id = ?)" +
изменил на join с подзапросом

2023-06-12 19:47 UTC, alexache requested changes

2023-06-12 19:47 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        genreStorage.getGenresByFilmId(resultSet.getLong("film_id"))
Это до сих пор проблема - запрос к базе в цикле, Нужно вынести обращение к стораджу жанров из этого метода, Для одиночного фильма (и переноса обращения к стораджу жанров в сервис или в метод стораджа) это все решит сразу, а вот для списка фильмов нужен еще метод получение списка жанров по списку фильмов

2023-06-12 20:46 UTC, VladislavKubarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        genreStorage.getGenresByFilmId(resultSet.getLong("film_id"))
Правильно ли я понимаю, что этот метод достаточно перенести в filmService в методе получения фильма по id ?

2023-06-13 15:18 UTC, alexache requested changes

2023-06-13 15:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            filmList.forEach(film -> film.getGenres().addAll(genreStorage.getGenresByFilmId(film.getId())));
Да, это все еще не то, запрос к базе в цикле остался, 
Нужен метод в genreStorage Map<Integer, List<Genre>> getGenresByFilmIds(List<Integer> filmIds), который будет по списку айди фильмов возвращать маппинг айди фильма на список жанров,
Внутри метода нужен запрос вида select fg.film_id, g.genre_id, g.name from GENRES g, FILM_GENRES fg where fg.genre_id= g.genre_idAND fg.film_id in (1,2,3)  - осталось сформировать список айди для такого запроса, а результат разложить в финальную мапу

2023-06-14 17:37 UTC, alexache approved these changes

2023-06-18 16:47 UTC, merged